-- +goose Up
-- Upgrade legacy records table (payload-only) to the current schema.
ALTER TABLE records DROP COLUMN IF EXISTS payload;

ALTER TABLE records ADD COLUMN IF NOT EXISTS uuid UUID;
ALTER TABLE records ADD COLUMN IF NOT EXISTS operation SMALLINT;
ALTER TABLE records ADD COLUMN IF NOT EXISTS status SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE records ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE records ADD COLUMN IF NOT EXISTS entity_type VARCHAR(32);
ALTER TABLE records ADD COLUMN IF NOT EXISTS entity_id BIGINT;
ALTER TABLE records ADD COLUMN IF NOT EXISTS amount NUMERIC(20, 8);
ALTER TABLE records ADD COLUMN IF NOT EXISTS currency CHAR(3);
ALTER TABLE records ADD COLUMN IF NOT EXISTS correlation_id UUID;
ALTER TABLE records ADD COLUMN IF NOT EXISTS comment TEXT;
ALTER TABLE records ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}';
ALTER TABLE records ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE records ADD COLUMN IF NOT EXISTS status_changed_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE records ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;

-- +goose Down
ALTER TABLE records DROP COLUMN IF EXISTS uuid;
ALTER TABLE records DROP COLUMN IF EXISTS operation;
ALTER TABLE records DROP COLUMN IF EXISTS status;
ALTER TABLE records DROP COLUMN IF EXISTS user_id;
ALTER TABLE records DROP COLUMN IF EXISTS entity_type;
ALTER TABLE records DROP COLUMN IF EXISTS entity_id;
ALTER TABLE records DROP COLUMN IF EXISTS amount;
ALTER TABLE records DROP COLUMN IF EXISTS currency;
ALTER TABLE records DROP COLUMN IF EXISTS correlation_id;
ALTER TABLE records DROP COLUMN IF EXISTS comment;
ALTER TABLE records DROP COLUMN IF EXISTS metadata;
ALTER TABLE records DROP COLUMN IF EXISTS updated_at;
ALTER TABLE records DROP COLUMN IF EXISTS status_changed_at;
ALTER TABLE records DROP COLUMN IF EXISTS completed_at;

ALTER TABLE records ADD COLUMN IF NOT EXISTS payload JSONB NOT NULL DEFAULT '{}';
